# Generated by Django 4.2 on 2023-04-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boa_app', '0002_remove_response_announce_announce_responses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='content',
            new_name='r_content',
        ),
        migrations.RemoveField(
            model_name='announce',
            name='responses',
        ),
    ]
