# Generated by Django 4.2 on 2023-04-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa_app', '0003_rename_content_response_r_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boa_app.author')),
                ('to_announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boa_app.announce')),
            ],
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
