# Generated by Django 4.2 on 2023-04-29 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boa_app', '0005_rename_responses_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='to_announce',
            new_name='announce',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='r_content',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='announce',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
