# Generated by Django 4.2 on 2023-05-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa_app', '0007_response_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boa_app.announce')),
            ],
        ),
    ]
